name = "AnalyzeWind"
uuid = "7cdb5f2e-e163-4828-890f-43dc181bcfdc"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "1.0.0-DEV"

[deps]
ControlPlots = "23c2ee80-7a9e-4350-b264-8e670f12517c"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[compat]
ControlPlots = "0.2.9"
NCDatasets = "0.14.8"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
